name: datn
description: A movie tickets booking and management application using Flutter and NestJS.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

# flutter packages pub run build_runner build --delete-conflicting-outputs
# (\w+):(\s+)([a-zA-Z\s\[\]|]+);
# $3 get $1;

dependencies:
  flutter_speed_dial: ^2.1.1
  firebase_core: ^1.0.1
  octo_image: ^1.0.0-nullsafety.1
  firebase_remote_config: ^0.9.0-dev.0
  flutter_cache_manager: ^3.0.0-nullsafety.1
  flutter_local_notifications: ^5.0.0-nullsafety.1
  firebase_messaging: ^9.0.0
  socket_io_client: ^0.9.12
  flutter_slidable: ^0.5.7
  url_launcher: ^6.0.2
  expandable: ^4.1.4
  meta: ^1.3.0
  flutter_rating_bar: ^4.0.0
  built_collection: ^5.0.0
  loading_indicator: ^1.2.0
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^5.0.0
  font_awesome_flutter: ^9.0.0-nullsafety
  image_picker: ^0.7.2+1
  cached_network_image: ^3.0.0-nullsafety
  firebase_storage: ^8.0.0
  flutter_dotenv: ^2.1.0
  flutter_google_places: 0.2.6
  datetime_picker_formfield: ^2.0.0
  intl: ^0.17.0
  tuple: ^2.0.0
  rxdart: ^0.26.0
  http: ^0.13.0
  firebase_auth: ^1.0.1
  built_value: ^8.0.2
  shared_preferences: ^2.0.4
  path_provider: ^2.0.1

  rx_redux: ^2.2.0-nullsafety.2
  distinct_value_connectable_stream: ^1.2.0-nullsafety.5
  flutter_provider: ^2.0.0
  rx_shared_preferences: ^2.0.0-nullsafety.0
  disposebag: ^1.5.0-nullsafety.1
  flutter_disposebag: ^1.1.0-nullsafety.1
  flutter_bloc_pattern: ^2.0.0
  rxdart_ext: ^0.0.1
  listenable_stream: ^1.0.0-nullsafety.1
  stream_loader: ^1.1.0-nullsafety.2

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pedantic: ^1.11.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dependency_overrides:
  flutter_google_places:
    git:
      url: https://github.com/hoc081098/flutter_google_places.git
      ref: 26ad86d26904113b143ca770e2e14b235d3230ba

dev_dependencies:
  build_runner: ^1.11.5
  built_value_generator: ^8.0.2

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - .prod.env
    - assets/images/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
flutter_intl:
  enabled: true
